version: '3'

services:
  poll:
    build: ./poll
    environment:
      - FLASK_ENV=production
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - poll-tier
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"