version: '3'

services:
  poll:
    build: ./poll
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - poll-tier
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  result:
    build: ./result
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - result-tier
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 20M

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      - back-tier
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: postgres:alpine
    networks:
      - result-tier
      - back-tier
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  db-data:

networks:
  poll-tier:

  result-tier:

  back-tier:
