version: '3'

services:
  poll:
    build: ./poll
    ports:
      - 80:80
    depends_on:
      - redis
    networks:
      - poll-tier

  result:
    build: ./result
    ports:
      - 4242:4242
    depends_on:
      - db
    networks:
      - result-tier

  worker:
    build: ./worker
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - back-tier

  redis:
    image: redis:alpine
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:alpine
    networks:
      - result-tier
      - back-tier
    ports:
      - 5432:5432
    restart: always
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data


networks:
  poll-tier:

  result-tier:

  back-tier:
