version: '3'

services:
  poll:
    build: ./poll
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - poll-tier

  result:
    build: ./result
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - result-tier

  worker:
    build: ./worker
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - back-tier

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:alpine
    networks:
      - result-tier
      - back-tier
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  poll-tier:

  result-tier:

  back-tier:
